### PR TITLE
Adjusted buildagent-generation-template.yml to work with new actions/running-images image directory structure.

### PR DESCRIPTION
**Pull request by erik-de-bont**
New build  buildagent-generation-template.yml  to solve issue l[https://github.com/YannickRe/azuredevops-buildagents/issues/70](https://github.com/YannickRe/azuredevops-buildagents/issues/70). During the transition period of the actions/runner-images  repository of migrating to the  new directory image structure the script can only be used for alpha images. The old script (renamed buildagent-generation-template-old ) should be use for pre-production and production image during this transition period.

### CODE REVIEW

**Comment by devneutz** [comment]
It seems in the meantime they also changed the folder structure for the release images: [https://github.com/actions/runner-images/pull/8627/](https://github.com/actions/runner-images/pull/8627)

**Comment by erik-de-bont** [comment]
> It seems in the meantime they also changed the folder structure for the release images: [https://github.com/actions/runner-images/pull/8627/](https://github.com/actions/runner-images/pull/8627)

That should mean than images created after November 15th have a production status. Hopefully  @YannickRe has time to merge my pull request, which shouldwork with the new file structure. I have currently tested it in two enviroments. In both I was able to generate new Windows and Linux runner images.

**Review by pippolino — COMMENTED** [review]
Hi Erik, why did you keep an old file?

**Comment by erik-de-bont** [comment]
> Hi Erik, why did you keep an old file?

At first only the alpha version was using  the new structure, but the pre-release and release were using the old structure. So we were in a transition fase. I just found out that the pre-release and release are now in the new format, so I will remove it.

**Comment by pippolino** [comment]
> At first only the alpha version was using the new structure, but the pre-release and release were using the old structure. So we are in a transition fase. I have removed it now.

The release version also uses the new structure. 

I'm trying your version and for now it works for ubuntu. I'll also try it for Windows.

**Comment by YannickRe** [comment]
@erik-de-bont thank you for the work. Is there a specific reason you switched to using the build-image.ps1 and measure-provisioners-duration.ps1 from the runner-images repo and not the one included in this repo?
I'm trying to assess what the risk is with switching to the one from MS vs staying with the one I had here originally.

**Comment by erik-de-bont** [comment]
@YannickRe  No, there is no specific reason. I just looked at the action/runner-images code and modified the scripts to make it work again with the new action/runner-images code.

**Comment by erik-de-bont** [comment]
@YannickRe  Do require additional information before accepting this pull request ?

**Comment by erik-de-bont** [comment]
Due to a change in the actions/runner-images repo the templates have been changed from *.json to pkr.hcl format for the alpha releses.. At the moment of writing this comment the pre-release and release are still using the json format. It usually takes 2-4 weeks  before the alpha images become release, so we are again in a transition period.

**Comment by YannickRe** [comment]
@erik-de-bont thanks for all the work! I do not require more information, I have been working long hours to go-live with my project. Soon I'll take 4 weeks vacation, and your work is the highest on my list to get out the door.

I'm sorry for the lack of interaction.

**Comment by YannickRe** [comment]
@erik-de-bont I finally got around to testing and merging it today. Thank you for all the hard work!

**Pull request merged**
