### PR TITLE
Added option to create Gallery VM

### PR DESCRIPTION
**Pull request by erik-de-bont**
Hi @YannickRe !

I have worked last couple of days on creating a combined version (VMSS or Gallery VM version).
I have made the following updates.

Split the pipelines up in the following stages:

- Build the Agent Pool VM
- Convert the VM to a Managed VM
- Connect the Managed VM to a VMSS, or update the GalleryVM image with a new version (depending on your input (vmss or galleryvm), when starting the pipeline.

I have also updated the README.MD with info about the required configuration settings.

### CODE REVIEW

**Comment by YannickRe** [comment]
Wow, @erik-de-bont , this is amazing! I'm very happy with the work you did, thank you for sharing it.
I am replying to let you know that my calendar is crazy busy for the next 2-3 weeks, so it might take a while before I can test and merge. Nonetheless, I am excited about this, and it will be great to have it!

**Comment by erik-de-bont** [comment]
@YannickRe  Thanks for the reply ! I took me quite some time to have the proper condition syntax for the last stage to select between vmss or galleryvm, but in the end I got it working. 
I also did some reverse engineering to see if i can get packer to create a managed vm in stead of a vhd. By the first looks at it, it seems like the modification should be made in the actions/runner-images make the modification in de json config file packer. Maybe I can create a workaround. But for now, the current solution works.

**Comment by erik-de-bont** [comment]
added a solution for issue [https://github.com/YannickRe/azuredevops-buildagents/issues/32](https://github.com/YannickRe/azuredevops-buildagents/issues/32). By adding a workaround task to avoid interference between Microsoft Defender for EndPoint and sysprep, which seems to cause this issue.

**Comment by YannickRe** [comment]
Soon, I promise! I'm overwhelmed with work and I can't currently spend the required time to go through this and see if it might have unintended consequences. Feel free to already try out this PR and let me know how it worked for you, I will take all feedback 🙂.

But again, I have NOT forgotten about this and I DO appreciate all the work that went into this.

**Comment by YannickRe** [comment]
@erik-de-bont Thank you very much for your work! It saved me an enormous amount of time.
It's merged as is, but it does have some backwards compatibility problems which I'm working through in another branch. Once I have those resolved, I will test out the Gallery functionality.

**Pull request merged**
